name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Apply Infra
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
      
      - name: Create tfvars file
        run: |
          echo 'db_username="${{ secrets.DB_USERNAME }}"' > terraform.tfvars
          echo 'db_password="${{ secrets.DB_PASSWORD }}"' >> terraform.tfvars
          echo 'public_key="${{ secrets.PUBLIC_KEY }}"' >> terraform.tfvars

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"

